---
title: "deitz_scratch_viz"
author: "Lauren Deitz"
date: "3/22/2022"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(stringr)
library(ggplot2)
library(magrittr)
```

## Reading in the Driver data

```{r}
drivers <- read.csv("../raw_data/drivers.csv")
qps <- read.csv("../raw_data/qualifying.csv")
pitstops <- read.csv("../raw_data/pit_stops.csv")
standings <- read.csv("../raw_data/driver_standings.csv")
races <- read.csv("../raw_data/races.csv")
```

## viz

pole position
```{r}
qp_drivers <- left_join(qps, drivers, by='driverId')

qp_drivers %>% filter(position == 1) %>% group_by(driverRef) %>% summarise(pole_position=n()) %>% 
  arrange(-pole_position) %>% 
  ggplot(.,aes(x=driverRef,y=pole_position)) + geom_bar(stat='identity') + coord_flip()
```
qualifying positions

```{r}
library(chron)
qp_drivers %>% group_by(driverRef) %>% mutate(avg_q1=mean(times(q1)))
## can't figure out how to handle the timeseries data!

```

pit stops
```{r}
pt_drivers <- left_join(pitstops, drivers, by="driverId")
pt_drivers %>% group_by(driverRef) %>% summarise(shortest=min(milliseconds)) %>% arrange(shortest)
pt_drivers %>% group_by(driverRef) %>% summarise(avg_pt = mean(milliseconds)) %>% arrange(avg_pt)

avg_shortest_pt <- pt_drivers %>% group_by(driverRef,stop) %>% summarise(avg_pt = mean(milliseconds)) %>% arrange(driverRef,avg_pt) %>% mutate(pt_rank=row_number(avg_pt)) %>% filter(pt_rank==1)
avg_shortest_pt %>% group_by(stop) %>% summarise(stop_count=n()) %>% ggplot(.,aes(x=stop,y=stop_count)) + geom_bar(stat='identity') + ggtitle('Shortest pit stop on average by driver')

avg_shortest_pt
```

standings over time
```{r}
race_standings <- left_join(standings, races, by="raceId")
driver_race_standings <- left_join(race_standings, drivers, by="driverId")

races2021 <- driver_race_standings %>% filter(year==2021)
races2019 <- driver_race_standings %>% filter(year==2019)

ggplot(races2021, aes(x=date,y=position,group=driverRef, color=driverRef)) + geom_line() + coord_flip() + ggtitle("2021")
ggplot(races2019, aes(x=date,y=position,group=driverRef, color=driverRef)) + geom_line() + coord_flip() + ggtitle("2019")

```

points over time
```{r}
ggplot(races2021, aes(x=date,y=points,group=driverRef,color=driverRef)) + geom_point() + geom_smooth(se=FALSE) + coord_flip() + ggtitle("2021")
ggplot(races2019, aes(x=date,y=points,group=driverRef,color=driverRef)) + geom_point() + geom_smooth(se=FALSE) + coord_flip() + ggtitle("2019")

```

pit stops over time
```{r}
pt_drivers <- left_join(pitstops, drivers, by="driverId")
pt_driver_races <- left_join(pt_drivers, races, by="raceId")

pt_2021 <- pt_driver_races %>% filter(year==2021)
pt_2019 <- pt_driver_races %>% filter(year==2019)

pt_2021 %>% group_by(driverRef,stop) %>% summarise(avg_pt = mean(milliseconds)) %>% arrange(driverRef,avg_pt)

```